### ISSUE TITLE
kayafirat.com

### ISSUE THREAD

**Issue by firatkaya1** [nkoehring/250kb-club#103]
https://kayafirat.com

uncompressed file size : 64 kb 
compressed file size : 41.8 kb  https://gtmetrix.com/reports/kayafirat.com/QBUUr5n5/

**Comment by nkoehring** [comment]
nice layout, there are some glitches though. The menü in the mobile layout is broken (at least in the mobile view from dev tools) and some scroll heights are a bit off. Adding it anyways.
