### ISSUE TITLE
parts.horse

### ISSUE THREAD

**Issue by duckinator** [nkoehring/250kb-club#108]
https://parts.horse

https://gtmetrix.com/reports/parts.horse/hn6zqvh7/ (homepage, 1.81KB)
https://gtmetrix.com/reports/parts.horse/1Iz3YZEX/ (individual component page, 12.3KB)

**Comment by nkoehring** [comment]
I'm using the https://parts.horse/parts page because it has at least some content. Maybe consider adding some explanation in the index page?
