### ISSUE TITLE
Consider adding https://majiehong.com/

### ISSUE THREAD

**Issue by Jiehong** [nkoehring/250kb-club#115]
Hi,

Would you mind considering adding https://majiehong.com/ ?

19KB transferred, 30KB uncompressed.

This stays true for almost any child page on that website.

For example https://majiehong.com/post/2020-10-03_reducing_this_blog_size/ is 112KB/326KB.

**Comment by nkoehring** [comment]
Added! Nice blog post btw. More people should read it!
