### ISSUE TITLE
my-flow.com

### ISSUE THREAD

**Issue by my-flow** [nkoehring/250kb-club#119]
Link to GTMetrix results: https://gtmetrix.com/reports/www.my-flow.com/4gBJSDzN/

```
- domain: my-flow.com
  url: https://www.my-flow.com
  size: 231.8 KB (237.9 KB Uncompressed)
```

**Comment by nkoehring** [comment]
85% of those 230kb are web fonts. I'm sure there is a lot of potential for savings. I'm adding the page anyways.
