### ISSUE TITLE
Addition of https://paulwilde.uk

### ISSUE THREAD

**Issue by pswilde** [nkoehring/250kb-club#123]
Hello,

Please would you consider adding my website to the 250kb.club list?
https://paulwilde.uk
Size (GTMetrix) compressed: 20.4KB
Size (GTMetrix) uncompressed: 27.6KB
GTMetrix link: https://gtmetrix.com/reports/paulwilde.uk/Y5Jx7r9s/

Thanks

**Comment by nkoehring** [comment]
Added. But please fix the top menu colours in dark mode.
