### ISSUE TITLE
Add lo.hn

### ISSUE THREAD

**Issue by Lohn** [nkoehring/250kb-club#124]
Please add my personal site https://lo.hn

6.2kb uncompressed 

https://gtmetrix.com/reports/lo.hn/RLchIhIl/

**Comment by nkoehring** [comment]
Wow, that domain name! Lucky shot? And nice to see that you self-host all the things! Definitely added.

**Comment by Lohn** [comment]
Thanks! I got it when Honduras lost control of the .hn to ICANN about ten years ago. 
And yes. I like to self host everything.
