### ISSUE TITLE
zn80.net

### ISSUE THREAD

**Issue by cblte** [nkoehring/250kb-club#128]
Hello. I redesigned my whole page and I would like to be part of your community. 
Here is a link to the latest GTmetrix result

GTmetrix: https://gtmetrix.com/reports/zn80.net/rVJDGEUL/
Domain: zn80.net
URL: https://zn80.net
size: 73.7
uncompressed: 80.6

**Comment by nkoehring** [comment]
Nice! Good use of simple but pleasant layout that doesn't distract from the content. Although I have a feeling that it is not necessary to have all three font variants loaded. Sorry, I'm nitpicking here. Added!

**Comment by cblte** [comment]
Good morning,
thank you very much for approving my site. 
With the fonts, you might be right. I will investigate a little bit. Also i am not sure, if preload is the best solution here.

**Comment by nkoehring** [comment]
I would suggest to use preload for the main font, because it is really used everywhere and you want to minimize the FOUT (or FOIT, if you're not using `font-style: swap`). But preloading too many things would render it useless.

**Comment by nkoehring** [comment]
Hello @cblte . Unfortunately your submitted page doesn't load anymore, so it has to be removed :(

**Comment by cblte** [comment]
HI there. I know. It was because of a power outage we had and should be fixed by now.
