### ISSUE TITLE
Add kishvanchee.com

### ISSUE THREAD

**Issue by kishvanchee** [nkoehring/250kb-club#131]
Hey, can you please add my site?

Site: [kishvanchee.com](kishvanchee.com)
GTMetrix: [https://gtmetrix.com/reports/kishvanchee.com/BvzDeiTf/](https://gtmetrix.com/reports/kishvanchee.com/BvzDeiTf/)
Size (compressed): 1.6

**Comment by nkoehring** [comment]
Minimalistic but informative! Added.
