### ISSUE TITLE
add quitsocialmedia.club

### ISSUE THREAD

**Issue by xplosionmind** [nkoehring/250kb-club#133]
[quitsocialmedia.club](https://quitsocialmedia.club 'Quit Social Media') has [a landing page](https://quitsocialmedia.club 'Quit Social Media') which [weights 75KB.2](https://gtmetrix.com/reports/quitsocialmedia.club/D6HAxbnx/ 'GTX Metrics score') (uncompressed) and its [main page](https://quitsocialmedia.club/home 'Quit Social Media Home') [weights 108.1KB](https://gtmetrix.com/reports/quitsocialmedia.club/XWVomyS7/ 'GTX Metrics score') (uncompressed)

**Comment by nkoehring** [comment]
Intriguing title already. I hate the cursor though. Changing the cursor to something that is invisible on parts off the page puts me off. Still adding it though. Maybe you can fix that cursor though?

**Comment by xplosionmind** [comment]
Fixed! Thanks a lot for the suggestion.  
Have a nice day!
