### ISSUE TITLE
Update for editions-du-26-octobre

### ISSUE THREAD

**Issue by cara-tm** [nkoehring/250kb-club#139]
Hi.

We made a lot of optimization to reduce the website weight despite large amount of content and features.

We totalize now **182.7 Kb** (uncompressed) within the home page: https://gtmetrix.com/reports/editions-du-26-octobre.com/I9c2CID7/

Please, could you update our score? Thank you lot.

Best regards,
Patrick.

**Comment by nkoehring** [comment]
Congrats! Good work making such a page so much more accessible on slow networks!

**Comment by cara-tm** [comment]
Thank you lot! ;)
