### ISSUE TITLE
Add artemislena.eu and gtrr.artemislena.eu

### ISSUE THREAD

**Issue by artemislena** [nkoehring/250kb-club#142]
https://artemislena.eu and https://gtrr.artemislena.eu.

GTMetrix: https://gtmetrix.com/reports/artemislena.eu/cq4LYF2k/ and https://gtmetrix.com/reports/gtrr.artemislena.eu/h3NctbC3/

**Comment by nkoehring** [comment]
Thanks for your contribution. I hope especially that second page is of good use to many!
