### ISSUE TITLE
Please add hmbrg.xyz

### ISSUE THREAD

**Issue by fr-an-kh** [nkoehring/250kb-club#154]
- domain: hmbrg.xyz
  url: https://hmbrg.xyz/
  uncompressed size: 1.65 kbyte
  **compressed size: 915 byte**
  last_checked: 2021-09-07

gtmetrix report: https://gtmetrix.com/reports/hmbrg.xyz/Ya4ywhDv/

**Comment by nkoehring** [comment]
Done!
