### ISSUE TITLE
miku86.com

### ISSUE THREAD

**Issue by miku86** [nkoehring/250kb-club#158]
Domain: miku86.com
GTMetrix: https://gtmetrix.com/reports/miku86.com/1zEQLchr/

Thanks :)

**Comment by nkoehring** [comment]
Added! I use Zola as well btw. Before I had a static (handknitted HTML) homepage on https://koehr.in and a [WriteFreely](https://writefreely.org/) blog on https://koehr.tech. Now with Zola, things are much simpler but I need to set up a nicer way to update my blog.

**Comment by miku86** [comment]
Thanks!
Yes, Zola is awesome. Coming from Typescript with React and Gatsby made the build-time really slow.
Have to add some 100 old posts, hope Zola can handle this better.

**Comment by nkoehring** [comment]
100 posts is easy. Zola does that in under a second. I once wrote my own blog engine in Rust. It handled around 100k posts in two or so seconds. I bet Zola can compete with that.
