### ISSUE TITLE
Phate6660.github.io

### ISSUE THREAD

**Issue by Phate6660** [nkoehring/250kb-club#159]
URL: https://Phate6660.github.io
GTMetrix: https://gtmetrix.com/reports/phate6660.github.io/UPJyZZ0H
Uncompressed size: 87.4KB

**Comment by nkoehring** [comment]
Added. But you need to be careful with the "friends" github profile pictures. One or two more would push the page over the edge (unless chrome is used, thanks to avif... what an awesome format!)
