### ISSUE TITLE
webzine.puffy.info

### ISSUE THREAD

**Issue by B4rb3rouss** [nkoehring/250kb-club#160]
url : https://webzine.puffy.cafe
size : 6.06 uncompressed
GTMetrix : https://gtmetrix.com/reports/webzine.puffy.cafe/4SmjYWKc/

**Comment by nkoehring** [comment]
Sorry, but the page is dead?

**Comment by B4rb3rouss** [comment]
Sorry, I'm too stupid : I fixed the link.
