### ISSUE TITLE
New site : si3t.ch

### ISSUE THREAD

**Issue by B4rb3rouss** [nkoehring/250kb-club#176]
* url : https://si3t.ch/
* GTMetrix : 2.47KB uncompressed

**Comment by nkoehring** [comment]
Bienvenue au club des 250kb! If that is not a good french, then please blame deepl.com :D

**Comment by B4rb3rouss** [comment]
> Bienvenue au club des 250kb! If that is not a good french, then please blame deepl.com :D
> 
Nice! Thanks a lot :)
Perfect french ;)
