### ISSUE TITLE
New site: pools.xmr.wiki

### ISSUE THREAD

**Issue by 00-matt** [nkoehring/250kb-club#190]
URL: https://gtmetrix.com/reports/pools.xmr.wiki/i37kTIds/

GTmetrix reports that the biggest page, the homepage, requires a 6.48 KB download which decompresses to 15.9 KB: https://gtmetrix.com/reports/pools.xmr.wiki/i37kTIds/

**Comment by nkoehring** [comment]
Welcome to the 250kb Club!
