### ISSUE TITLE
New site: alefvanoon.xyz

### ISSUE THREAD

**Issue by alefvanoon** [nkoehring/250kb-club#202]
https://alefvanoon.xyz
Pingdom test: 57.9 KB
https://tools.pingdom.com/#5fa084aec7400000

**Comment by nkoehring** [comment]
Nice and simple page. But the tiny images you list in the footer are actually pretty huge and could be much smaller. (1300px wide big brother is watching you?)

**Comment by nkoehring** [comment]
Page unfortunately not reachable anymore :(
