### ISSUE TITLE
oopsallmarquees.com

### ISSUE THREAD

**Issue by nmpennypacker** [nkoehring/250kb-club#210]
URL: https://oopsallmarquees.com
Size 699B
Not much else to say. It's just a lot of marquees.

GTMetrix: https://gtmetrix.com/reports/oopsallmarquees.com/UFJRUpey/

**Comment by nkoehring** [comment]
Welcome to the 250kb club! The direct link to your page will be https://250kb.club/oopsallmarquees-com
