### ISSUE TITLE
New Website Suggestion -> https://palashbauri.in

### ISSUE THREAD

**Issue by bauripalash** [nkoehring/250kb-club#215]
It's my blog; about philosophy, psychology, and society around us, and of course science/tech

URL: https://palashbauri.in
size: 32.8kb (uncompressed) and 17.4kb compressed

GTMetrix Report: https://gtmetrix.com/reports/palashbauri.in/IY6SuhZt/

**Comment by nkoehring** [comment]
Welcome to the 250kb club! The direct link to your entry will be https://250kb.club/palashbauri-in
