### ISSUE TITLE
Website Suggestion (cri.cl)

### ISSUE THREAD

**Issue by dejalavidavolar** [nkoehring/250kb-club#217]
Hi, I would like to be part of 250kb club! This is my blog.

https://cri.cl

Gtmetrix: https://gtmetrix.com/reports/cri.cl/mqXdKL1y/ (99kb)

Regards!

**Comment by nkoehring** [comment]
Welcome to the 250kb club! The direct link to your entry will be https://250kb.club/cri-cl
