### ISSUE TITLE
add: https://youkwhd.vercel.app/

### ISSUE THREAD

**Issue by youkwhd** [nkoehring/250kb-club#218]
the size should be **221 KB** uncompressed according to https://gtmetrix.com/reports/youkwhd.vercel.app/leXSZ2qZ/

or this test: https://yellowlab.tools/result/g88sinszob

**Comment by nkoehring** [comment]
Even with all those Gifs on the bottom, over 60% of your page is just webfonts. I'm pretty sure there is a better way than loading almost 140kb webfonts.

**Comment by nkoehring** [comment]
Couldn't see any improvement, so I'm closing this for now. Please create a new Issue after you updated your page.
