### ISSUE TITLE
New site: davidjenei.com

### ISSUE THREAD

**Issue by davidjenei** [nkoehring/250kb-club#227]
I'd love to join!

https://gtmetrix.com/reports/davidjenei.com/tqHJ52wj/

Domain: davidjenei.com
URL: https://davidjenei.com
Size: 17.8KB
Uncompressed: 21.9KB

**Comment by nkoehring** [comment]
Nice page! Welcome to the 250kb Club. Your direct link will be https://250kb.club/davidjenei-com
