### ISSUE TITLE
Please add zinzy.website

### ISSUE THREAD

**Issue by zinzy** [nkoehring/250kb-club#229]
I'm back! Thanks for your feedback on my project back then, I appreciate the work you do.

**Comment by nkoehring** [comment]
Welcome back! I'll add the page. Your direct link will be https://250kb.club/zinzy-website
You might want to check if you could do something against loading over 40kb of JSON though.

**Comment by nkoehring** [comment]
Oh one more thing (Apart that I love your profile pic... those glasses are incredible!)
Some links on your page point to the original markdown file path (for example on the "now" page). You might want to check what's going on there.
