### ISSUE TITLE
Add aroace.space

### ISSUE THREAD

**Issue by foreverxml** [nkoehring/250kb-club#234]
Hello! I would like to issue an application to join the 250kb Club. My website is <https://aroace.space> and is 186kb large uncompressed last I have checked. Thank you!

**Comment by nkoehring** [comment]
Nice style! Welcome to the 250kb Club!
The direct URL will be https://250kb.club/aroace-space

Btw: You use your avatar picture as favicon. Unfortunately at least firefox loads it twice this way. Clearly a bug of the browser but still something that is easy to fix.
