### ISSUE TITLE
add ExpeditionSasquatch.org and ajroach42.com

### ISSUE THREAD

**Issue by ajroach42** [nkoehring/250kb-club#236]
I got small websites, it would be neat to see them featured here.
![Screenshot from 2022-05-29 12-14-34](https://user-images.githubusercontent.com/10469165/170879919-36cfaa7a-65c7-4c02-a4a8-39c11a183945.png)
![Screenshot from 2022-05-29 12-14-14](https://user-images.githubusercontent.com/10469165/170879921-a6d8c344-2ae7-4c6c-9668-bbe5a67fd99a.png)

**Comment by nkoehring** [comment]
Not sure what you did but expeditionsasquatch.org currently loads over 1MB of compressed data.

http://ajroach42.com/ will be added. The direct URL will be https://250kb.club/ajroach42-com
