### ISSUE TITLE
add jasonsanta.xyz

### ISSUE THREAD

**Issue by jason123santa** [nkoehring/250kb-club#240]
https://jasonsanta.xyz
53.1kb uncompressed 

https://gtmetrix.com/reports/jasonsanta.xyz/rfBjEggF

**Comment by nkoehring** [comment]
Welcome to the 250kb Club!
The direct URL will be https://250kb.club/jasonsanta-xyz

**Comment by jason123santa** [comment]
Is there anything I can add to my website? Like some kind of sticker or do just a link to the 250kb website?

**Comment by nkoehring** [comment]
Do you want a sticker? I saw that the 512kb club has badges. Is that something you'd like to have?

**Comment by nkoehring** [comment]
@jason123santa how about one of these?

![color_badge_bright](https://user-images.githubusercontent.com/246402/173180227-fbea9162-cd50-4f83-86f0-7c8a6137f536.png)
![color_badge_dark](https://user-images.githubusercontent.com/246402/173180228-0e61ea05-0826-48df-842f-24215bf56b14.png)
![simple_badge_bright](https://user-images.githubusercontent.com/246402/173180229-0718e32a-f22b-4bbd-95c2-0fb9c0afc8ce.png)
![simple_badge_dark](https://user-images.githubusercontent.com/246402/173180230-3436b0ba-75e1-423d-b4d2-1e4c51911381.png)

**Comment by jason123santa** [comment]
yeah that works thanks
