### ISSUE TITLE
Add theden.sh

### ISSUE THREAD

**Issue by TheDen** [nkoehring/250kb-club#276]
Please add [theden.sh](https://theden.sh/)

~~Results https://yellowlab.tools/result/geant2d5yp total weight is `160KB`~~ Did some updates

Results https://yellowlab.tools/result/gegpt43zer total weight is `76.4 KB`

**Comment by nkoehring** [comment]
Hello @TheDen . Your page size grow over the threshold (it is the "currently listening to" collage) and has to be removed, unfortunately. Please reopen this issue or create a new one, if you want to rejoin! Looking forward to have your fantastic homepage again.
