### ISSUE TITLE
http://buoy.hopto.org

### ISSUE THREAD

**Issue by hatonthecat** [nkoehring/250kb-club#285]
http://buoy.hopto.org/About/Sol.htm <700 bytes Thank you!

**Comment by nkoehring** [comment]
Website not reachable.

**Comment by hatonthecat** [comment]
I closed the website a couple months ago as I repurposed the Raspberry Pi. I uploaded a copy of the page source: https://github.com/hatonthecat/hatonthecat.github.io/blob/main/bouyant.htm It was actually based on a hybrid of two other sites: https://github.com/hatonthecat/hatonthecat.github.io/blob/main/source.htm no need to reopen. Thanks for checking.
