### ISSUE TITLE
Please add page.

### ISSUE THREAD

**Issue by drewaaaaa** [nkoehring/250kb-club#309]
Hi!

Please add site https://kookoomyawka.my1.ru/clock.html to list.

DebugBear said it has 180kb size of page (but source code is only 965 bytes).
https://www.debugbear.com/test/website-speed/w6cxqr5h/overview?info=labOverview

Thank you.

**Comment by nkoehring** [comment]
Hi! Most of the size comes from the huge favicon! Maybe you can change something about that.
Apart from that: Welcome to the 250kb club!
