### ISSUE TITLE
a new website to add

### ISSUE THREAD

**Issue by kaedeisafox** [nkoehring/250kb-club#311]
hello! can you please add https://txt.allfoxesare.gay ?
it's only 127.8kb
thanks! :3

**Comment by nkoehring** [comment]
Its even smaller! Just under 9kb :tada: 
Welcome to the club!

**Comment by kaedeisafox** [comment]
hello, I moved the website to the second-level domain aka https://allfoxesare.gay
could you please edit it in your directory? thanks!
