### ISSUE TITLE
Add vanzasetia.site

### ISSUE THREAD

**Issue by vanzasetia** [nkoehring/250kb-club#318]
Here are the details:

- Domain: https://vanzasetia.site/
- Size: 33.7KB (compressed size)
- GTmetrix report: https://gtmetrix.com/reports/vanzasetia.site/QDbN6H5S/

Thank you for creating and maintaining 250kb.club website! I hope you are doing great.

**Comment by nkoehring** [comment]
Welcome to the 250kb club. Your page entry will be https://250kb.club/vanzasetia-site/
