### ISSUE TITLE
Adds https://drag13.io

### ISSUE THREAD

**Issue by Drag13** [nkoehring/250kb-club#320]
# [https://drag13.io](https://drag13.io) - 36.4kb

My perosnal [blog ](https://drag13.io) is only 36.4 kB uncompressed when loading initial view and 178kB if you scroll till the end of the page.

Seems to be a good candidate, doesn't it?

**Comment by nkoehring** [comment]
Clearly a good candidate! Welcome to the 250kb club. Your page entry will be https://250kb.club/drag13-io/
