### ISSUE TITLE
Modify thelazysre.com

### ISSUE THREAD

**Issue by voioo** [nkoehring/250kb-club#321]
👋🏻 Hi, could you please modify my website please?

- https://thelazysre.com (38KB uncompressed)
- GTMetrix: https://gtmetrix.com/reports/thelazysre.com/MUa1GvO5/
- YellowLab Tools: https://yellowlab.tools/result/gjnxtw91c9

**Comment by nkoehring** [comment]
As long as the URL isn't changed, everything should be updated more or less weekly: https://250kb.club/thelazysre-com/
