### ISSUE TITLE
Add markus-haack.com

### ISSUE THREAD

**Issue by mhaack** [nkoehring/250kb-club#323]
Here are the details of my personal site:

Domain: https://markus-haack.com/
Size: 118KB (compressed size)
GTmetrix report: https://www.debugbear.com/test/website-speed/ejc3kPpm/overview

Thank you for maintaining 250kb.club.

**Comment by nkoehring** [comment]
Welcome to the 250kb club. Your page entry will be https://250kb.club/markus-haack-com/
