### ISSUE TITLE
Add bmoat.com

### ISSUE THREAD

**Issue by kujaomega** [nkoehring/250kb-club#326]
https://bmoat.com/ is 23.4KB according to yellowlab.tools: https://yellowlab.tools/result/gkadc899mf/rule/totalWeight

**Comment by kujaomega** [comment]
PR added https://github.com/nkoehring/250kb-club/pull/327

**Comment by nkoehring** [comment]
Your Favicon is almost 30kb. Maybe try a modern format. It looks like SVG or even PNG might be a good choice.
Anyway: Welcome to the 250kb Club! Your sub page will be https://250kb.club/bmoat-com
