### ISSUE TITLE
Add noelle.df1.dev

### ISSUE THREAD

**Issue by dualfighter1** [nkoehring/250kb-club#329]
https://noelle.df1.dev/ is 188KB according to yellowlab.tools: https://yellowlab.tools/result/gkfc9xkqqq/rule/totalWeight

![image](https://user-images.githubusercontent.com/70805001/234805459-8f944535-ac0f-4070-9840-af54362624c5.png)

**Comment by nkoehring** [comment]
Welcome to the 250kb Club! Your sub page will be https://250kb.club/noelle-df1-dev
