### ISSUE TITLE
Add jakk.dev

### ISSUE THREAD

**Issue by Jakk01** [nkoehring/250kb-club#332]
Please can you add my site?

https://jakk.dev/ is 3.3KB according to Yellowlab.tools:
https://yellowlab.tools/result/glyl7atbt6/rule/totalWeight

Thanks!

**Comment by Jakk01** [comment]
Hey, I did some editing and now the page is a bit bigger. Here is the new version:

https://jakk.dev/ is 3.4KB according to yellowlab.tools: https://yellowlab.tools/result/gllcsrnllp/rule/totalWeight

Thanks

**Comment by nkoehring** [comment]
Welcome to the 250kb Club! Your page will be https://250kb.club/jakk-dev/
