### ISSUE TITLE
Add blog.skiserv.eu

### ISSUE THREAD

**Issue by skiserv** [nkoehring/250kb-club#335]
My blog is [1.5KB on the Yellow Lab test](https://yellowlab.tools/result/gl53zdoudk/rule/totalWeight) : [https://blog.skiserv.eu/](https://blog.skiserv.eu/)
Thanks

**Comment by nkoehring** [comment]
Welcome to the 250kb Club! Your page will be https://250kb.club/blog-skiserv-eu/

**Comment by skiserv** [comment]
Thanks !
