### ISSUE TITLE
Re-add theden.sh

### ISSUE THREAD

**Issue by TheDen** [nkoehring/250kb-club#337]
Please re-add [theden.sh](https://theden.sh/)

Following from https://github.com/nkoehring/250kb-club/issues/276. I didn't want to remove the "currently listening to" collage, so we wrote a new highly optimised service that generates better collages https://github.com/SongStitch/song-stitch 

Results https://yellowlab.tools/result/glbmmcgowk total weight is `168 KB`

**Comment by TheDen** [comment]
I've updated it recently and now it's `123 KBs` https://yellowlab.tools/result/gmn7g96f3p

**Comment by TheDen** [comment]
Did some more optimisations and now it's 88KBs! https://yellowlab.tools/result/gmqhf9ppdu

**Comment by nkoehring** [comment]
Fantastic! That is the stuff I am here for! :popcorn: 
Welcome back to the 250kb Club!
