### ISSUE TITLE
Add code.strigo.cc

### ISSUE THREAD

**Issue by akarzim** [nkoehring/250kb-club#338]
https://code.strigo.cc is 109Kb according to Yellow Lab Tools: https://yellowlab.tools/result/glv84lechi

![image](https://github.com/nkoehring/250kb-club/assets/130560/69fa6af1-093e-4ab8-b081-645cd10b90ca)

**Comment by nkoehring** [comment]
Welcome to the 250kb Club! Your page will be https://250kb.club/code-strigo-cc/
