### ISSUE TITLE
Add https://privacyfreak84.github.io

### ISSUE THREAD

**Issue by privacyfreak84** [nkoehring/250kb-club#340]
My personal website.
Only 12.9 kb uncompressed according to GTMetrix: https://gtmetrix.com/reports/privacyfreak84.github.io/RVTEdEyU/

**Comment by nkoehring** [comment]
Not exactly true, because there is an almost 150kb picture of a seamonkey. But still fits, so **welcome to the 250kb club!** Maybe think about shrinking that picture. It is a 1200x675px image shown in a 200x112px box.
