### ISSUE TITLE
add https://foxhaven.cyou

### ISSUE THREAD

**Issue by aysilu-kitsune** [nkoehring/250kb-club#350]
the page: https://foxhaven.cyou
the test results: https://yellowlab.tools/result/gni4s2bgt9

thanks!

**Comment by nkoehring** [comment]
Thank you for your submission. The page technically fits the criteria, so first of all: Welcome to the 250kb Club! But I would like to see some more optimization work done. There are quite some things that could be much smaller, without changing the page's appearance.

**Comment by aysilu-kitsune** [comment]
what are they? i am kinda new to website building...
I suppose I could make contacts logos smaller?

**Comment by nkoehring** [comment]
Yes, those images are all pretty big compared to how they are presented.
![image](https://github.com/nkoehring/250kb-club/assets/246402/40b064a1-9b91-43af-af94-fe5bf3877ac5)
