### ISSUE TITLE
Add httpguides.com

### ISSUE THREAD

**Issue by jmstfv** [nkoehring/250kb-club#356]
* https://httpguides.com
* Yellow Lab: https://yellowlab.tools/result/go8n6brgrh
* GTmetrix: https://gtmetrix.com/reports/httpguides.com/8l6vybLx/

**Comment by nkoehring** [comment]
Welcome to the 250kB Club! Your sub-page will be https://250kb.club/httpguides-com

I see, you've set up goatcounter on your own domain. Does it work via a redirect, or is it possible to host by yourself?

**Comment by jmstfv** [comment]
> I see, you've set up goatcounter on your own domain. Does it work via a redirect, or is it possible to host by yourself?

I self-host it. It shows more accurate stats that way.

**Comment by nkoehring** [comment]
Welcome to the 250Kb Club! Your page will be https://250kb.club/httpguides-com
Nice page btw, super useful. I actually used it from time to time since a bit already.

**Comment by jmstfv** [comment]
happy to hear that!

If you have any suggestions, do let me know. i haven't updated it for a while.
