### ISSUE TITLE
My website: brunofontes.net

### ISSUE THREAD

**Issue by brunofontes** [nkoehring/250kb-club#373]
Hello,

The compressed size of [my website](https://brunofontes.net) is 175KB (https://gtmetrix.com/reports/brunofontes.net/9TrlTWSV/). Would it be possible to add my website in the list?

Many thanks!
Bruno

**Comment by nkoehring** [comment]
Welcome to the 250kB Club! Your sub-page will be https://250kb.club/brunofontes-net

**Comment by brunofontes** [comment]
Thank you, Norman! :)
