### ISSUE TITLE
Add rb.ax

### ISSUE THREAD

**Issue by steelcutoatmeal** [nkoehring/250kb-club#376]
To my esteemed colleagues,

Please consider my website for entry into your venerable and _trim_ private club:

```
  url: https://rb.ax/
  size: 2.9 KB
  last_checked: 2023-12-02
```

https://yellowlab.tools/result/gr5j05m0t4

**Comment by nkoehring** [comment]
Welcome to the 250Kb Club! Your page will be https://250kb.club/rb-ax
