### ISSUE TITLE
Add tienbuigia.online

### ISSUE THREAD

**Issue by tienbuigia** [nkoehring/250kb-club#378]
URL: [tienbuigia](https://tienbuigia.online)
Yellow Lab: https://yellowlab.tools/result/grcddb283s
Gtmetrix: https://gtmetrix.com/reports/tienbuigia.online/8Na8Sb5R/
PageSpeed: https://pagespeed.web.dev/analysis/https-tienbuigia-online/ji6tcz48u4?form_factor=mobile

Note: the gtmetrix link is the old result, they want me to upgrade to Pro to re-test, since I tested too many websites. What difference is I resize my image, the size reduce significantly.

**Comment by nkoehring** [comment]
Welcome to the 250Kb Club! Your page will be https://250kb.club/tienbuigia-online

**Comment by tienbuigia** [comment]
I'm sorry, how long do I have to wait for the [link](https://250kb.club/tienbuigia-online) to my website to work? I think it is cool and I want to link it to my homepage.
