### ISSUE TITLE
Add vinc.cc

### ISSUE THREAD

**Issue by vinc** [nkoehring/250kb-club#385]
https://vinc.cc is is my personal website, it weights 61.1 KB.

**Comment by nkoehring** [comment]
Almost too minimalistic, but because your sub pages are still by far inside the limit, I added the page anyway (also it's beautiful!)
Thank you for your contribution and welcome to the 250kB Club!
Your sub page will be https://250kb.club/vinc-cc

**Comment by vinc** [comment]
Thanks :) The goal is indeed to have most pages of the website under the limit!

The majority of pages without images should not change the total much, and I'm experimenting with adding dithering+compression for most of the rest.

**Comment by nkoehring** [comment]
Unfortunately, there was an issue with requesting your page. Is there maybe some access restriction for automated crawlers? 250kB Club uses Phantomas with User-Agent set to "250kb-club".

**Comment by nkoehring** [comment]
The issue disappeared, so welcome, now for real!
