### ISSUE TITLE
Add sappho.io

### ISSUE THREAD

**Issue by sapphonie** [nkoehring/250kb-club#389]
Weight is 134 KB with yellowlabs.

**Comment by nkoehring** [comment]
Welcome to the 250kB Club! Your sub page will be https://250kb.club/sappho-io

**Comment by nkoehring** [comment]
Okay, there is an issue with your page, unfortunately. My local instance of YLT is reading your page as 334kB in size, which is suspiciously close to the uncompressed size. I need to investigate that.

**Comment by sapphonie** [comment]
Weird, it might be google's stupid analytics stuff interfering. I'll also
take a look

**Comment by sapphonie** [comment]
Slimmed it down by removing google analytics / excessive cloudflare cdn stuff. Should top out at ~198kb compressed according to firefox's network tab. Yellowlabs says 27.8kb but that's not correct, I'm serving a ~165kb mp4 that's loading lazily so it should be that plus content.

https://yellowlab.tools/result/gstelnbcde

**Comment by nkoehring** [comment]
Works! Thanks for your effort and welcome again, to the 250kB Club!
