### ISSUE TITLE
https://mylight.website/

### ISSUE THREAD

**Issue by kevquirk** [nkoehring/250kb-club#39]

**Comment by nkoehring** [comment]
Would be so much lighter without those huge web fonts. But I agree that they look great!

**Comment by kevquirk** [comment]
> Would be so much lighter without those huge web fonts. But I agree that they look great!

Yep, 75KB of the total size (84.7KB) is fonts. I wouldn't call them "huge" though, and the aesthetic they add is worth it, I thought. :-)

https://gtmetrix.com/reports/mylight.website/ECGde82U/
