### ISSUE TITLE
Add https://andrekelling.de

### ISSUE THREAD

**Issue by AndreKelling** [nkoehring/250kb-club#390]
that's my personal website.

the homepage is quite minimal in content but all subsites are also below 250kb with images.

here is a check on cloudflares and yellowlab url scanner for the homepage:

- https://radar.cloudflare.com/scan/82e57f3a-9da6-44bc-b0c9-51781123f388 (currently 35kb)
- https://yellowlab.tools/result/gshj4pvjf1 (currently 15.6kb)

here a check of the biggest subsite:

- https://radar.cloudflare.com/scan/9368343e-9536-40d3-b53b-055a428a07f2/summary (currently 130kb)
- https://yellowlab.tools/result/gshj8e8m0u (currently 151kb)

there is also inline styles used here which will fake the current calculated content ratio. :-/

**Comment by nkoehring** [comment]
So well made!
Welcome to the 250kB Club! Your sub page will be https://250kb.club/andrekelling-de
