### ISSUE TITLE
Add varchar.neocities.org

### ISSUE THREAD

**Issue by varchar1337** [nkoehring/250kb-club#393]
Weight 55.5KB according to Cloudflare https://radar.cloudflare.com/scan/265b44e8-684a-41cb-804d-b4339c58b474/summary

**Comment by nkoehring** [comment]
Nice design, but a little empty. But because all the sub pages with content are still under 100kb...
Welcome to the 250kB Club! Your sub page will be https://250kb.club/varchar-neocities-org
