### ISSUE TITLE
add luke.marzen.me

### ISSUE THREAD

**Issue by lmarzen** [nkoehring/250kb-club#396]
[luke.marzen.me](https://luke.marzen.me)

size: 82.4 KB

https://yellowlab.tools/result/gssa7vunpo

**Comment by nkoehring** [comment]
That is a pretty keyboard! I still prefer my Sofle v2, though.
Welcome to the 250kB Club! Your sub page will be https://250kb.club/luke-marzen-me

**Comment by lmarzen** [comment]
Good choice. I think I will try something similar for my next keyboard. At the very least, I want to try a split.
