### ISSUE TITLE
Add: https://alexalejandre.com/

### ISSUE THREAD

**Issue by veqqq** [nkoehring/250kb-club#398]
https://alexalejandre.com/

12.12kb on the network, 25.41 uncompressed: https://radar.cloudflare.com/scan/e9acab72-6798-494a-b322-2298cdb6798b/summary

Thank you!

**Comment by nkoehring** [comment]
Nice and clean! Welcome to the 250kB Club! Your sub-page will be https://250kb.club/alexalejandre-com
