### ISSUE TITLE
Add daudix.codeberg.page

### ISSUE THREAD

**Issue by daudix** [nkoehring/250kb-club#399]
[daudix.codeberg.page](https://daudix.codeberg.page)

size: 57.4 KB

https://yellowlab.tools/result/gsy3rdbssd

**Comment by nkoehring** [comment]
I love the style, but 200kb background images are a no no, sorry :shrug:

**Comment by daudix** [comment]
Yeah, I've opened this issue before the redesign and forgot to close it, sorry :(

Your website is really nice! Maybe I'll implement something like this :)
