### ISSUE TITLE
http://stratus3d.com/

### ISSUE THREAD

**Issue by Stratus3D** [nkoehring/250kb-club#40]
My blog is approximately 48.66KB.

**Comment by nkoehring** [comment]
Really nice. It would be even better if you would load content outside of the view later. Especially graphics. The cool thing here is that most browsers natively support that by now (only Safari still hides it behind a flag). Just add `loading="lazy"` attribute to your images and the browser is figuring it out for you.

**Comment by Stratus3D** [comment]
I've been meaning to ditch all the images in the header area. I've removed most of them but there are still a couple hanging around. I'd also like to replace the background images with just SVG noise.
