### ISSUE TITLE
Add archaeoramblings.com

### ISSUE THREAD

**Issue by andreatitolo** [nkoehring/250kb-club#402]
Hi! I would like to add [archaeoramblings.com](https://www.archaeoramblings.com)

Size: 6.6 KB

Report: https://yellowlab.tools/result/gtiterb909

**Comment by nkoehring** [comment]
Welcome to the 250kB Club! Your sub-page will be https://250kb.club/archaeoramblings-com

**Comment by andreatitolo** [comment]
Thanks! :) I've noticed the link you provided points to a download? (It will download an empty file with the website name) 
I am experiencing this also for the other websites added recently here, is it a build process or a bug?
