### ISSUE TITLE
add new domain/url - timikels.com/blog/

### ISSUE THREAD

**Issue by obdude** [nkoehring/250kb-club#405]
Hey Norman!

I came across your directory of epic websites (the 256kb club), and it got me thinking - my site, [timikels.com/blog/](http://timikels.com/blog/), might be a good fit.

It focuses on helping creators and authors with simple tech... My hope is that it becomes a helpful resource and a dash of inspiration for others interested in similar things.

If you think it aligns with the spirit of your directory, I'd be honored to be included. No worries if not - I appreciate you taking the time to consider it!

Best,
Tim

P.S. Gruesse in die Hauptstadt aus Vientiane, Laos.

**Comment by nkoehring** [comment]
Hey Tim,

Generally the page fulfills the criteria for the 250kB Club, but its focus puts me a bit off. I might be damaged from the wave of advertisement, the internet currently is. Let me know, if you think I'm wrong, and I'll reconsider.

**Comment by obdude** [comment]
No worries, thanks anyway, Norman!

Cheers,
Tim
