### ISSUE TITLE
Add to alpha.rsw.jp

### ISSUE THREAD

**Issue by yamadasanngongon** [nkoehring/250kb-club#406]
Adayo.client.jp has moved to alpha.rsw.jp

I’d be happy if you could add it again.

This site is for Japan.

**Comment by nkoehring** [comment]
Hmm, somehow your page loads [this huge graphic](https://alpha.rsw.jp/image/jh.png), shows it for a second and then hides it?

**Comment by nkoehring** [comment]
Now the page is almost empty :shrug:
