### ISSUE TITLE
Add notes.ghed.in

### ISSUE THREAD

**Issue by rghedin** [nkoehring/250kb-club#413]
My personal/tech blog. I'm a Brazilian journalist covering tech.

[Notes by Rodrigo Ghedin](https://notes.ghed.in)

**Comment by nkoehring** [comment]
I suggest you to change the social icons color to white dark mode. They are very low in contrast, otherwise. My suggestion: include the SVG markup directly into the page and set the path's stroke (or fill) to `currentColor`, which takes the font color.
Welcome to the 250kB Club!

**Comment by rghedin** [comment]
That a very good advice, @nkoehring! Thanks, I'll try to implement it.
