### ISSUE TITLE
Suggesting janilowski.pl

### ISSUE THREAD

**Issue by janilowski** [nkoehring/250kb-club#415]
Hello,
I would like to submit my website: [janilowski.pl](https://janilowski.pl)
According to [CloudFlare](https://radar.cloudflare.com/scan/0a46b727-dacf-4deb-842b-4842d778d7aa/summary) it's currently about 70,89kB in total.

**Comment by nkoehring** [comment]
Hello, I might want to minimize the SVG markup. You made them yourself with Inkscape, I guess? If you look at the markup of the SVG file, you'll see a lot of useless stuff in there. I suggest you to throw it into a tool like https://jakearchibald.github.io/svgomg/ for example. Also your image tag has width and height set to crazy values. SVG is size agnostic though, so I would recommend removing those numbers. But anyway... 

Welcome to the 250kB Club!
