### ISSUE TITLE
Suggest maniek86.xyz

### ISSUE THREAD

**Issue by maniekx86** [nkoehring/250kb-club#422]
URL: https://maniek86.xyz
Yellow Lab Tools: https://yellowlab.tools/result/gw4r3imn7y (26.5 KB)

Also I might suggest https://retro.maniek86.xyz too (my different site on my domain, even smaller than main)
Yellow Lab Tools: https://yellowlab.tools/result/gw4r2driwb (15 KB)

**Comment by nkoehring** [comment]
Welcome to the 250kB Club! Both pages are added now. Love the retro version!
