### ISSUE TITLE
Suggesting chromora.com

### ISSUE THREAD

**Issue by PrimaryCat** [nkoehring/250kb-club#423]
I made this FOSS color palette generator with HTML, CSS and Vanilla JS, the focus was for it to be lightweight and it turned out to be light enough for the club! I feel like it would be a good addition.

https://chromora.com/

Cloudflare reports 218.97kb. Thank you for your consideration!

**Comment by nkoehring** [comment]
Nice! I love to add useful web tools! Welcome to the 250kB Club!
