### ISSUE TITLE
Requesting sharavananpa.dev to be added

### ISSUE THREAD

**Issue by sharavananpa** [nkoehring/250kb-club#427]
**url: [https://sharavananpa.dev/](https://sharavananpa.dev/)**
**Total weight: 5.6KB**

[yellow lab report](https://yellowlab.tools/result/gwn8abjdm2)

[cloudflare report](https://radar.cloudflare.com/scan/aa3b6e87-3318-4313-94e1-fb14266a14d7/summary)

**Comment by nkoehring** [comment]
Welcome to the 250kB Club!

**Comment by sharavananpa** [comment]
Thank you!
