### ISSUE TITLE
Add processwire.dev

### ISSUE THREAD

**Issue by MoritzLost** [nkoehring/250kb-club#44]
My [ProcessWire tutorial website processwire.dev](https://processwire.dev/) qualifies for this site, please add it!

* **Domain name:** [processwire.dev](https://processwire.dev/)
* **GTMetrix results:** [https://gtmetrix.com/reports/processwire.dev/qeRiPjF6/](https://gtmetrix.com/reports/processwire.dev/qeRiPjF6/)

114.3 KB uncompressed!

**Comment by nkoehring** [comment]
I really like the design. The only thing bugging me is that the script of [Matamo Analytics](https://matomo.org/) eats up almost 30kb even after compression.
