### ISSUE TITLE
 Personal website submission

### ISSUE THREAD

**Issue by wisehackermonkey** [nkoehring/250kb-club#445]
Love the project, I made this website. and would love to put it into the ring for a website submission
# submission:
https://wisehackermonkey.github.io/website/

# 2.2kb in size. 
### Loads fast on dialup speeds!

Thanks for taking the time to review.

best,
- oran

**Comment by nkoehring** [comment]
Welcome to the 250kB Club!

**Comment by wisehackermonkey** [comment]
OMG AWESOME!
