### ISSUE TITLE
fs2f.github.io

### ISSUE THREAD

**Issue by fs2f** [nkoehring/250kb-club#456]
:-) home page is 688b (as stated), contact is 308b, software is 748b, css is 446b (2190b total, 2,1kb)

**Comment by fs2f** [comment]
main site is now 1Kb due to me adding an ascii

**Comment by fs2f** [comment]
https://yellowlab.tools/result/h031ayypys
i keep changing my page too much

**Comment by nkoehring** [comment]
There's also basically no content. But alright, I like it. Welcome to the 250kB Club! You'll find your page at https://250kb.club/fs2f-github-io
