### ISSUE TITLE
Add tiagorangel.com

### ISSUE THREAD

**Issue by tiagorangel1** [nkoehring/250kb-club#458]
15kB :) https://tiagorangel.com

![image](https://github.com/user-attachments/assets/d61a5a36-0ae1-4fc2-a01d-ed9f9ce8318d)

btw is there a something like this but for websites even smaller than 250kb?

**Comment by tiagorangel2011** [comment]
wait is it 568 KB or 15kb?

**Comment by nkoehring** [comment]
It is over 500kB, sorry. The web font alone is almost 350kB.
