### ISSUE TITLE
Add bbbhltz.codeberg.page

### ISSUE THREAD

**Issue by bbbhltz** [nkoehring/250kb-club#461]
url: bbbhltz.codeberg.page
size: 57.32 kB
size according to Firefox
CloudFlare says 72.71 kB 
https://radar.cloudflare.com/scan/af5b8375-6ddf-4f29-a878-2d270161afbf

Good work on keeping this list up to date

**Comment by nkoehring** [comment]
Great content, thank you for sharing!
Welcome to the 250kB Club! You'll find your page at https://250kb.club/bbbhltz-codeberg-page

**Comment by bbbhltz** [comment]
Thanks. I actually have a domain now at https://bobbyhiltz.com
