### ISSUE TITLE
add icpmol.es

### ISSUE THREAD

**Issue by icpmoles** [nkoehring/250kb-club#463]
Site: https://icpmol.es/
Size: 56.6 KB
Test results: https://yellowlab.tools/result/h11481sp4m/rule/totalWeight

**Comment by nkoehring** [comment]
You have two rather large images in there that look like they don't need to be that large. Maybe it's worth investigating.
Anyway, welcome to the 250kB Club! You'll find your page at https://250kb.club/icpmol-es
