### ISSUE TITLE
Page doesn't work without JavaScript

### ISSUE THREAD

**Issue by Fanael** [nkoehring/250kb-club#50]
This is essentially a static page, but it still requires javascript, which is known to be [unreliable](https://kryogenix.org/code/browser/everyonehasjs.html), to show the list. Please consider generating the DOM ahead of time and only using javascript for where client side scripting is very useful, like sorting the list after the user switches the sorting criterion.

**Comment by nkoehring** [comment]
Hi @Fanael . Yes I agree that the page should be rendered ahead of time and I'm working on this. I just don't have a lot of spare time at the moment. You can [join the discussion](https://lobste.rs/s/cs42ck/250kb_club) if you have further ideas or issues.

**Comment by nkoehring** [comment]
Fixed by https://github.com/nkoehring/250kb-club/commit/b00b6286b148e65a603967cff6d2534d8df4c783
