### ISSUE TITLE
https://tom.kobalt.dev/

### ISSUE THREAD

**Issue by TomKTW** [nkoehring/250kb-club#51]
Size of index page should be around 2.3kB compressed (5.5kB uncompressed), but the index is mostly empty as I'm trying to separate stuff around instead of bundling things on index to keep things minimal if possible (the content rating may be concerning with this part). In general, pages should have resources inlined where possible (to require at least one request) and size may vary around 5-25kB compressed (except for actual project pages that may require additional stuff to work with or cannot be inlined).

**Comment by nkoehring** [comment]
Thanks for the request. Instead of the mostly empty index page I put a link to https://tom.kobalt.dev/map into the list, which gives a lot more meaningful content and is still very small. Maybe you want to consider this to be your index?

**Comment by TomKTW** [comment]
> Maybe you want to consider this to be your index?

Considering that I don't have any better use case for index at this moment, it should be a good idea to put it like that. I've redirected and moved content from /map to index. If it's okay like this, you can update the link without "/map" in it.
