### ISSUE TITLE
denv.it

### ISSUE THREAD

**Issue by denysvitali** [nkoehring/250kb-club#56]
(my personal website)

https://denv.it

68.07 KB transferred (70.97 KB)

**Comment by nkoehring** [comment]
Wow, you're loading 70kb just to show your name and mail address. It looks great but that is so not the purpose of 250kb.club.
But I will add [your blog URL](https://denv.it/blog/) which can offer much more with even a bit less transferred data.

**Comment by denysvitali** [comment]
I'll fix ot someday. It's just because of Google fonts unfortunately :(
