### ISSUE TITLE
https://nest.jakl.one/

### ISSUE THREAD

**Issue by jaklt** [nkoehring/250kb-club#60]
uncompressed size is 23.1KB

**Comment by nkoehring** [comment]
Thanks for this submission. I'm a big fan of ActivityPub and the ideas behind it as well, so I'm looking forward to look through your posts!

**Comment by jaklt** [comment]
Thanks for adding me! In fact, it's more an [Indieweb](https://indieweb.org/) site which I've set up to just repost some of the things to Mastodon too.
