### ISSUE TITLE
https://gallant.dev

### ISSUE THREAD

**Issue by agallant** [nkoehring/250kb-club#61]
https://gtmetrix.com/reports/gallant.dev/jtJkNvVj/ (9.56kb)

Thanks!

**Comment by nkoehring** [comment]
Added!
I love the idea of using a repeating gradient for the scan-line effect. Some people with visual impairment might have a problem with the overall readability though. My suggestion would be to brighten the link colour a bit, for example to `#AED6FF`.

**Comment by agallant** [comment]
Yeah, I do need to tweak the CSS a bit more, and appreciate the feedback. I agree with the link color being lighter, but still want it to be a *tad* darker just to distinguish from the regular text. Also agreed on fixing the background, just had to stop being lazy and read the CSS docs for how :)

Thanks again!
