### ISSUE TITLE
https://ache.one

### ISSUE THREAD

**Issue by arobase-che** [nkoehring/250kb-club#68]

**Comment by nkoehring** [comment]
Added! That brought me to the idea to add a language flag to the list. Thanks.

**Comment by arobase-che** [comment]
That sounds like a really good idea ! :D

Be careful using flags of country, they don't associate well with languages (🇫🇷 is for France, not french language, 🇮🇳 have to many languages to be specific).
But if by flag, you mean [flag](https://en.wikipedia.org/w/index.php?title=Flag_(computing)&redirect=no). Then, you can use [ISO-639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) as a tag, and it would be nice !

**Comment by nkoehring** [comment]
That's a very valid point! Thanks for making it. I'll go for iso language codes instead then.
