### ISSUE TITLE
Please add my blog to 250KB club

### ISSUE THREAD

**Issue by xpil** [nkoehring/250kb-club#70]
Hi.

My blog address is https://xpil.eu

The total uncompressed size is approximately 220KB: https://gtmetrix.com/reports/xpil.eu/lwhCcnEF/

Please consider adding it to the 256KB club list.

Thanks!

**Comment by nkoehring** [comment]
Added! Nice to see, that Wordpress can deliver such a small frontend!

**Comment by xpil** [comment]
> Nice to see, that Wordpress can deliver such a small frontend! I don't know if you made that theme yourself. But if so, you might consider removing jquery and rewrite the few scripts you have to use native APIs instead. That would save you another 60kb or maybe even some more.

It is a premium theme from Themegraphy. I removed some of the underlying JS/CSS (as well as >200kB of fonts) to make it a bit smaller but can't remove jquery for it drives the comments system on the blog. And my dev knowledge of web stuff is close to none so I wouldn't have a clue how to rewrite these few scripts.

Happy to stay at 220KB.

Thanks!

**Comment by nkoehring** [comment]
The pages are updated regularly. For now every week but I might tweak that number at some point. So the change in size will be reflected soon.
