### ISSUE TITLE
adding oh.mg

### ISSUE THREAD

**Issue by mrmannet** [nkoehring/250kb-club#71]
Hello,

Not exactly sure if I'm doing this right, my githubbery isn't tip top 😅 

I'd like to add my site https://oh.mg/ it's 15,7kb uncompressed according to https://gtmetrix.com/reports/oh.mg/uP7gozNl/

Many thanks !

**Comment by nkoehring** [comment]
🙌 Congrats, you're now a proud member of The 250KB Club 🙌
