### ISSUE TITLE
Data on https://250kb.club/ seems outdated

### ISSUE THREAD

**Issue by susam** [nkoehring/250kb-club#83]
Consider the data for https://danluu.com/ appearing on https://250kb.club/ that shows 3 KB content size and 100% content ratio. But in reality, this page has 22 KB content-size and 13% content-ratio. Here are the steps to reproduce on a local system:

 1. Run `yarn dev` locally.
 2. Visit http://localhost:3000/. The row for danluu.com shows 3 KB content-size and 100% content-ratio.
 2. Run `node compile-list.mjs` now. Wait for it to complete.
 3. Refresh http://localhost:3000/ again. It now shows the correct data for `danluu.com`, i.e., 22 KB content-size and 13% content-ratio.

The timestamp for this entry in `src/components/pages.mjs` shows 1608071620875, i.e., Tue Dec 15 22:33:40 UTC 2020, so that entry is now older than 7 days.

Here is an example standalone script that shows the same observation regarding content-weight and content-ratio:

```js
const phantomas = require('phantomas')
const fs = require('fs')

async function getMetrics(url) {
  const results = await phantomas(url)
  const m = results.getMetrics()
  const extraWeight = m.cssSize + m.jsSize + m.webfontSize + m.otherSize
  const contentWeight = m.htmlSize + m.jsonSize + m.imageSize + m.base64Size + m.videoSize
  const totalWeight = extraWeight + contentWeight

  console.log('cssSize:', m.cssSize)
  console.log('jsSize:', m.jsSize)
  console.log('webfontSize:', m.webfontSize)
  console.log('otherSize:', m.otherSize)
  console.log('htmlSize:', m.htmlSize)
  console.log('jsonSize:', m.jsonSize)
  console.log('imageSize:', m.imageSize)
  console.log('base64Size:', m.base64Size)
  console.log('videoSize:', m.videoSize)

  console.log('extraWeight:', extraWeight)
  console.log('contentWeight:', contentWeight)
  console.log('totalWeight:', totalWeight)
}

getMetrics('https://danluu.com/')
```

Output:

```
cssSize: 0
jsSize: 19218
webfontSize: 0
otherSize: 203
htmlSize: 2897
jsonSize: 0
imageSize: 0
base64Size: 0
videoSize: 0
extraWeight: 19421
contentWeight: 2897
totalWeight: 22318
```

**Comment by nkoehring** [comment]
Whoops, didn't run the cron job :D thanks for the heads up!
