### ISSUE TITLE
I would like to join the Club

### ISSUE THREAD

**Issue by cara-tm** [nkoehring/250kb-club#84]
Please, could you add this website (listed in the 512Kb Club)?

* Domain name: editions-du-26-octobre.com
* GTMetrix results: https://gtmetrix.com/reports/editions-du-26-octobre.com/QTaCMkUv/
* Uncompressed page size: 223.4 Kb

Thank you.

**Comment by nkoehring** [comment]
Lots of content in 200kb, great!

**Comment by cara-tm** [comment]
Thanks!
