### ISSUE TITLE
love the concept, submitting my blog

### ISSUE THREAD

**Issue by aminozuur** [nkoehring/250kb-club#90]
Eftegarie: https://eftegarie.com
92KB uncompressed, proof: https://gtmetrix.com/reports/eftegarie.com/jCdlPiFn/

-----
Furthermore, a tiny suggestion:
The number one is currently: https://h3liu.ml/
It's just a webpage that says _"I'll probably use this domain for shitposting or do random stuff with it idk."_, and links to "My actual website".

Although there is nothing wrong with that, it might be sensible to introduce a rule whereby only _real_ websites are allowed, that have a genuine purpose (other than being a parked domain).

**Comment by nkoehring** [comment]
Hi! Thanks for that. When I initially added h3liu.ml this wasn't the case, so thanks for this. I will remove it for now. By the way: I actually check most of the websites by hand. It is an exclusive club after all.
