### ISSUE TITLE
Temp.sh

### ISSUE THREAD

**Issue by meme-lord** [nkoehring/250kb-club#91]
Domain name: Temp.sh
GTMetrix results: https://gtmetrix.com/reports/temp.sh/UyhSWvve/
Uncompressed page size: 25.6kb

**Comment by nkoehring** [comment]
I love this kind of services! Is this open source? Would totally host it for myself.

**Comment by meme-lord** [comment]
It's not open source atm but I'm planning on making it open source at some point
