### ISSUE TITLE
Typo in project description

### ISSUE THREAD

**Issue by cadars** [nkoehring/250kb-club#92]
“Inspired by **Bredley Taunts** 1MB.club”

It's Bradley Taunt > https://github.com/bradleytaunt

**Comment by nkoehring** [comment]
You are right. I there's an apostrophe missing! Thanks.

**Comment by cadars** [comment]
The name is misspelled in the README too.

**Comment by nkoehring** [comment]
Thanks again!

**Comment by cadars** [comment]
You're welcome Narmon.
