### ISSUE TITLE
zwieratko.sk

### ISSUE THREAD

**Issue by zwieratko** [nkoehring/250kb-club#94]
[zwieratko.sk](https://zwieratko.sk)

28.2 KB - unxompressed

[GTmetrix result](https://gtmetrix.com/reports/zwieratko.sk/AR4ul508/)

**Comment by nkoehring** [comment]
Sorry, but your page throws a ton of CSP errors. I'd like to see that fixed before adding it. But please don't fix it by removing or over-relaxing the CSP headers. Would be a shame.
