### ISSUE TITLE
decentnet.github.io

### ISSUE THREAD

**Issue by decentnet** [nkoehring/250kb-club#96]
- https://decentnet.github.io/
- GTMetrix: https://gtmetrix.com/reports/decentnet.github.io/9rBp0Ers/
- Main page: 10.1 KB compressed
- Main page: 30.6 KB uncompressed
- Whole website: 120.2 KB uncompressed
- No JavaScript

**Comment by nkoehring** [comment]
Would love to see more of this kind!
