### ISSUE TITLE
codingotaku.com

### ISSUE THREAD

**Issue by codingotaku** [nkoehring/250kb-club#98]
| Domain | Compressed Size | GTMetrix |
|:-----------|:-------------------------|:-------------|
| https://codingotaku.com | 13.8 KB | https://gtmetrix.com/reports/codingotaku.com/QGwHlW0N/ |

**Comment by codingotaku** [comment]
It's amazing how much size can be reduced by redrawing and SVG image from scratch.

**Comment by nkoehring** [comment]
Great work!
