### ISSUE TITLE
allien.work

### ISSUE THREAD

**Issue by AllienWorks** [nkoehring/250kb-club#99]
Hello,

I'd like to apply to the club with https://allien.work site:

- https://gtmetrix.com/reports/allien.work/tXdyECge/
- Total Page Size - 124KB

Cheers!

**Comment by AllienWorks** [comment]
@nkoehring hey, thanks for the compliment! Glad you like it, I just redesigned it few weeks back.

I'm aware of the fonts and I will probably reduce it in the future. I'm using variable fonts for many widths and I couldn't really cherry-pick the character subsets for it, so had to include it whole unfortunately.

You'd probably argue I shouldn't use it at all, but I always said that it's elementary for a good design to have a beautiful font :)

**Comment by nkoehring** [comment]
No I generally agree with you. A good font is a big part of good design. But there is rarely the need for three full blown web fonts. I personally for example switched all my defaults in the browser to more pleasant fonts (mainly Libertinus) because it makes such a difference for me.
